services:
  - type: web
    name: telebot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python src/main.py
    envVars:
      - key: BOT_TOKEN
        sync: false
    healthCheckPath: /health
    disk:
      name: telebot-data
      mountPath: /opt/render/project/src/data
      sizeGB: 1